export default {
  ACTION_FAILED: 'ACTION_FAILED',
  SET_APP_STATE: 'SET_APP_STATE',
  SET_COIN_LIST: 'SET_COIN_LIST',
  SET_SELECTED_COINS: 'SET_SELECTED_COINS',
  SET_BITCOIN: 'SET_BITCOIN',
  SET_VIEW: 'SET_VIEW',
};
