const ACTION_TYPES = {
  SET_OVERVIEW_STATE: 'SET_OVERVIEW_STATE',
  GET_OVERVIEW_API_FAIL: 'GET_OVERVIEW_API_FAIL',
  SET_MORE_INFO_STATE: 'SET_MORE_INFO_STATE',
  GET_MORE_INFO_API_FAIL: 'GET_MORE_INFO_API_FAIL',
};
