export default {
  ACTION_FAILED: 'ACTION_FAILED',
  SET_APP_STATE: 'SET_APP_STATE',
  SET_COIN_LIST: 'SET_COIN_LIST',
  SET_VIEW: 'SET_VIEW',
  /*
  SET_OVERVIEW_STATE: 'SET_OVERVIEW_STATE',
  GET_OVERVIEW_API_FAIL: 'GET_OVERVIEW_API_FAIL',
  SET_MORE_INFO_STATE: 'SET_MORE_INFO_STATE',
  GET_MORE_INFO_API_FAIL: 'GET_MORE_INFO_API_FAIL',
  */
};
